#!/bin/bash

NIMBUS_CHILDOPTS=${NIMBUS_CHILDOPTS:-"-Xmx1024m"}
sed -i -e "s/%NIMBUS_CHILDOPTS%/$NIMBUS_CHILDOPTS/g" $STORM_HOME/conf/storm.yaml

DRPC_CHILDOPTS=${DRPC_CHILDOPTS:-"-Xmx768m"}
sed -i -e "s/%DRPC_CHILDOPTS%/$DRPC_CHILDOPTS/g" $STORM_HOME/conf/storm.yaml

SUPERVISOR_CHILDOPTS=${SUPERVISOR_CHILDOPTS:-"-Xmx256m"}
sed -i -e "s/%SUPERVISOR_CHILDOPTS%/$SUPERVISOR_CHILDOPTS/g" $STORM_HOME/conf/storm.yaml

WORKER_CHILDOPTS=${WORKER_CHILDOPTS:-"-Xmx768m"}
sed -i -e "s/%WORKER_CHILDOPTS%/$WORKER_CHILDOPTS/g" $STORM_HOME/conf/storm.yaml

UI_CHILDOPTS=${UI_CHILDOPTS:-"-Xmx768m"}
sed -i -e "s/%UI_CHILDOPTS%/$UI_CHILDOPTS/g" $STORM_HOME/conf/storm.yaml