#!/bin/bash

NIMBUS_RESOLVED_HOST=${NIMBUS_EXT_HOST:-${NIMBUS_PORT_6627_TCP_ADDR:-"UNAVAILABLE"}}
NIMBUS_RESOLVED_PORT=${NIMBUS_EXT_PORT:-${NIMBUS_PORT_6627_TCP_PORT:-"6627"}}

sed -i -e "s/%NIMBUS_HOST%/$NIMBUS_RESOLVED_HOST/g" $STORM_HOME/conf/storm.yaml
sed -i -e "s/%NIMBUS_PORT%/$NIMBUS_RESOLVED_PORT/g" $STORM_HOME/conf/storm.yaml