#!/bin/bash

ZOOKEEPER_RESOLVED_HOST=${ZOOKEEPER_EXT_HOST:-${ZOOKEEPER_PORT_2181_TCP_ADDR:-"UNAVAILABLE"}}
ZOOKEEPER_RESOLVED_PORT=${ZOOKEEPER_EXT_PORT:-${ZOOKEEPER_PORT_2181_TCP_PORT:-"2181"}}

sed -i -e "s/%ZOOKEEPER_HOST%/$ZOOKEEPER_RESOLVED_HOST/g" $STORM_HOME/conf/storm.yaml
sed -i -e "s/%ZOOKEEPER_PORT%/$ZOOKEEPER_RESOLVED_PORT/g" $STORM_HOME/conf/storm.yaml